# Generated by Django 5.0 on 2024-01-04 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('address_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=40, null=True)),
                ('voivodeship', models.CharField(max_length=40, null=True)),
                ('zip_code', models.CharField(max_length=60, null=True)),
                ('house_number', models.IntegerField(null=True)),
                ('apartment_number', models.IntegerField(null=True)),
                ('street', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('client_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=256, null=True)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterClient',
            fields=[
                ('newsletter_client_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=40)),
                ('netto_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brutto_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('size_s', models.IntegerField(default=0, verbose_name='S')),
                ('size_m', models.IntegerField(default=0, verbose_name='M')),
                ('size_l', models.IntegerField(default=0, verbose_name='L')),
                ('size_xl', models.IntegerField(default=0, verbose_name='XL')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=40)),
                ('last_name', models.CharField(default='', max_length=40)),
                ('account_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('has_account', models.BooleanField(default=False)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server_RestAPI.clientaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_datetime', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server_RestAPI.client')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=40)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('photo_name', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server_RestAPI.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server_RestAPI.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server_RestAPI.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='size_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server_RestAPI.size'),
        ),
    ]
