# Generated by Django 5.0 on 2024-01-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_RestAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderDetail',
        ),
    ]
