# Generated by Django 5.0 on 2024-01-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server_RestAPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
