# Generated by Django 5.0 on 2024-01-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server_RestAPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraccount",
            name="apartment_number",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="house_number",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="province",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="street",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
