# Generated by Django 5.0 on 2024-01-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server_RestAPI", "0002_customeraccount_apartment_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeraccount",
            name="phone",
            field=models.CharField(blank=True, default="111", max_length=15),
        ),
    ]
