# Generated by Django 5.0 on 2024-01-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_RestAPI', '0002_rename_orderitem_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_item_id',
            new_name='order_detail_id',
        ),
    ]
