# Generated by Django 5.0 on 2024-01-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server_RestAPI", "0003_customeraccount_remove_customer_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraccount",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
