# Generated by Django 5.0 on 2024-01-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_RestAPI', '0003_order_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='media/product_images/'),
        ),
    ]
