# Generated by Django 5.0 on 2024-01-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server_RestAPI", "0003_alter_customeraccount_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeraccount",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
    ]
