# Generated by Django 5.0 on 2024-01-15 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server_RestAPI", "0004_customeraccount_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customeraccount",
            name="last_login",
        ),
    ]
