# Generated by Django 5.0 on 2024-01-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server_RestAPI", "0005_remove_customeraccount_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeraccount",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customeraccount",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
