# Generated by Django 5.0 on 2024-01-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "server_RestAPI",
            "0007_customeraccount_groups_customeraccount_is_superuser_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
